services:
  test_many_non_main_files:
    build:
      dockerfile: docker/generic.dockerfile
      context: .
    entrypoint:
      - run_gradescope
    working_dir: /autograder/source
    volumes:
      - "./tests/e2e/test_many_non_main_files/results:/autograder/results"
      - "./tests/e2e/test_many_non_main_files/student_tests:/autograder/source/student_tests"
      - "./tests/e2e/test_many_non_main_files/submission:/autograder/submission"
      - "./tests/e2e/test_many_non_main_files/submission_metadata.json:/autograder/submission_metadata.json"
      - "./tests/e2e/integration_config.toml:/autograder/source/config.toml"

  test_requirements_in_submission:
    build:
      dockerfile: docker/generic.dockerfile
      context: .
    entrypoint:
      - run_gradescope
    working_dir: /autograder/source
    volumes:
      - "./tests/e2e/test_requirements_in_submission/results:/autograder/results"
      - "./tests/e2e/test_requirements_in_submission/student_tests:/autograder/source/student_tests"
      - "./tests/e2e/test_requirements_in_submission/submission:/autograder/submission"
      - "./tests/e2e/test_requirements_in_submission/submission_metadata.json:/autograder/submission_metadata.json"
      - "./tests/e2e/integration_config.toml:/autograder/source/config.toml"

  test_metadata_attack_volume_holder:
    build:
      context: ./tests/e2e/test_metadata_attack
      dockerfile_inline: |
        FROM busybox
        ADD submission_metadata.json /cache/submission_metadata.json
        CMD ["cp", "/cache/submission_metadata.json", "/autograder/submission_metadata.json"]
    volumes:
      - "metadata_attack_vol:/autograder/"
      

  test_metadata_attack:
    build:
      dockerfile: docker/generic.dockerfile
      context: .
    entrypoint:
      - run_gradescope
    working_dir: /autograder/source
    volumes:
      - "metadata_attack_vol:/autograder"
      - "./tests/e2e/test_metadata_attack/results:/autograder/results"
      - "./tests/e2e/test_metadata_attack/student_tests:/autograder/source/student_tests"
      - "./tests/e2e/test_metadata_attack/submission:/autograder/submission"
      - "./tests/e2e/integration_config.toml:/autograder/source/config.toml"
    depends_on:
      test_metadata_attack_volume_holder:
        condition: service_completed_successfully

  test_data_file_in_submission:
    build:
      dockerfile: docker/generic.dockerfile
      context: .
    entrypoint:
      - run_gradescope
    working_dir: /autograder/source
    volumes:
      - "./tests/e2e/test_data_file_in_submission/results:/autograder/results"
      - "./tests/e2e/test_data_file_in_submission/student_tests:/autograder/source/student_tests"
      - "./tests/e2e/test_data_file_in_submission/submission:/autograder/submission"
      - "./tests/e2e/test_data_file_in_submission/submission_metadata.json:/autograder/submission_metadata.json"
      - "./tests/e2e/integration_config.toml:/autograder/source/config.toml"

  test_build:
    build:
      dockerfile: docker/generic.dockerfile
      context: .
    entrypoint: build_autograder
    working_dir: /autograder/source
    command:
      - "-o"
      - "/autograder/bin"
    volumes:
      - "./tests/e2e/test_build/student_tests:/autograder/source/student_tests"
      - "./tests/e2e/test_build/bin:/autograder/bin"
      - "./tests/e2e/integration_config.toml:/autograder/source/config.toml"
      - "./tests/e2e/test_build/starter_code/:/autograder/source/starter_code"

  test_run_local:
    build:
      dockerfile: docker/generic.dockerfile
      context: .
    entrypoint: ["sh", "/app/entrypoint.sh"]
    working_dir: /app/source
    volumes:
      - "./tests/e2e/test_run_test_my_work/entrypoint.sh:/app/entrypoint.sh"
      - "./tests/e2e/test_run_test_my_work/results:/autograder/results"
      - "./tests/e2e/test_run_test_my_work/student_tests:/app/source/student_tests"
      - "./tests/e2e/test_run_test_my_work/submission:/app/submission"
      - "./tests/e2e/test_run_test_my_work/test_my_work_config.toml:/app/source/config.toml"

  test_run_local_nested:
    build:
      dockerfile: docker/generic.dockerfile
      context: .
    entrypoint: ["sh", "/app/entrypoint.sh"]
    working_dir: /app/source
    volumes:
      - "./tests/e2e/test_run_local_in_nested_with_data/entrypoint.sh:/app/entrypoint.sh"
      - "./tests/e2e/test_run_local_in_nested_with_data/results:/autograder/results"
      - "./tests/e2e/test_run_local_in_nested_with_data/student_tests:/app/source/student_tests"
      - "./tests/e2e/test_run_local_in_nested_with_data/submission:/app/submission"
      - "./tests/e2e/test_run_local_in_nested_with_data/test_my_work_config.toml:/app/source/config.toml"

  test_run_with_prairie_learn:
    build:
      dockerfile: docker/generic.dockerfile
      context: .
    entrypoint: run_prairielearn
    command:
      - --config-file
      - /grade/tests/config.toml
    working_dir: /grade
    volumes:
      - "./tests/e2e/test_run_with_prairie_learn/results:/grade/results"
      - "./tests/e2e/test_run_with_prairie_learn/student_tests:/grade/tests/student_tests"
      - "./tests/e2e/test_run_with_prairie_learn/submission:/grade/student"
      - "./tests/e2e/test_run_with_prairie_learn/data.json:/grade/data/data.json"
      - "./tests/e2e/integration_config.toml:/grade/tests/config.toml"

volumes:
  metadata_attack_vol: