services:
  test_many_non_main_files:
    build:
      dockerfile: gradescope.dockerfile
    volumes:
      - "./tests/e2e/test_many_non_main_files/results:/autograder/results"
      - "./tests/e2e/test_many_non_main_files/student_tests:/autograder/source/student_tests"
      - "./tests/e2e/test_many_non_main_files/submission:/autograder/submission"
      - "./tests/e2e/test_many_non_main_files/submission_metadata.json:/autograder/submission_metadata.json"
      - "./tests/e2e/integration_config.toml:/autograder/source/config.toml"

  test_requirements_in_submission:
    build:
      dockerfile: gradescope.dockerfile
    volumes:
      - "./tests/e2e/test_requirements_in_submission/results:/autograder/results"
      - "./tests/e2e/test_requirements_in_submission/student_tests:/autograder/source/student_tests"
      - "./tests/e2e/test_requirements_in_submission/submission:/autograder/submission"
      - "./tests/e2e/test_requirements_in_submission/submission_metadata.json:/autograder/submission_metadata.json"
      - "./tests/e2e/integration_config.toml:/autograder/source/config.toml"

  test_data_file_in_submission:
    build:
      dockerfile: gradescope.dockerfile
    volumes:
      - "./tests/e2e/test_data_file_in_submission/results:/autograder/results"
      - "./tests/e2e/test_data_file_in_submission/student_tests:/autograder/source/student_tests"
      - "./tests/e2e/test_data_file_in_submission/submission:/autograder/submission"
      - "./tests/e2e/test_data_file_in_submission/submission_metadata.json:/autograder/submission_metadata.json"
      - "./tests/e2e/integration_config.toml:/autograder/source/config.toml"

#  test_c_build:
#    build:
#      dockerfile: gradescope.dockerfile
#    volumes:
#      - "./tests/integration/test_c_build/results:/autograder/results"
#      - "./tests/integration/test_c_build/student_tests:/autograder/source/student_tests"
#      - "./tests/integration/test_c_build/submission:/autograder/submission"
#      - "./tests/integration/test_c_build/submission_metadata.json:/autograder/submission_metadata.json"
#      - "./tests/integration/test_c_build/config.toml:/autograder/source/config.toml"

  test_build:
    build:
      dockerfile: run.dockerfile
    command: 
      - "--build"
      - "-o"
      - "/app/bin"
    volumes:
      - "./tests/e2e/test_build/student_tests:/app/source/student_tests"
      - "./tests/e2e/test_build/bin:/app/bin"
      - "./tests/e2e/integration_config.toml:/app/source/config.toml"
      - "./tests/e2e/test_build/starter_code/:/app/source/starter_code"


  test_run_test_my_work:
    build:
      dockerfile: run.dockerfile
    entrypoint: ["/app/entrypoint.sh"]
    volumes:
      - "./tests/e2e/test_run_test_my_work/entrypoint.sh:/app/entrypoint.sh:777"
      - "./tests/e2e/test_run_test_my_work/results:/app/results"
      - "./tests/e2e/test_run_test_my_work/student_tests:/app/source/student_tests"
      - "./tests/e2e/test_run_test_my_work/submission:/app/submission"
      - "./tests/e2e/integration_config.toml:/app/source/config.toml"

