version: "3"
services:
  test_submission_name_with_spaces:
    profiles:
      - test
    build:
      dockerfile: Dockerfile
    entrypoint: /autograder/run_autograder
    volumes:
      - "./tests/integration/test_submission_name_with_spaces/results:/autograder/results"
      - "./tests/integration/test_submission_name_with_spaces/studentTests:/autograder/source/studentTests"
      - "./tests/integration/test_submission_name_with_spaces/submission:/autograder/submission"
      - "./tests/integration/test_submission_name_with_spaces/submission_metadata.json:/autograder/submission_metadata.json"
      - "./tests/integration/integration_config.toml:/autograder/source/config.toml"

  test_many_non_main_files:
    profiles:
      - test
    build:
      dockerfile: Dockerfile
    entrypoint: /autograder/run_autograder
    volumes:
      - "./tests/integration/test_many_non_main_files/results:/autograder/results"
      - "./tests/integration/test_many_non_main_files/studentTests:/autograder/source/studentTests"
      - "./tests/integration/test_many_non_main_files/submission:/autograder/submission"
      - "./tests/integration/test_many_non_main_files/submission_metadata.json:/autograder/submission_metadata.json"
      - "./tests/integration/integration_config.toml:/autograder/source/config.toml"

  test_build_move_test_cases:
    profiles:
      - test
    build:
      dockerfile: Dockerfile.build
    entrypoint: /app/run.sh
    volumes:
      - "./tests/integration/test_build_move_test_cases/studentTests:/app/source/studentTests"
      - "./tests/integration/test_build_move_test_cases/run.sh:/app/run.sh"
      - "./tests/integration/test_build_move_test_cases/bin:/app/bin"

  test_build_move_starter_code:
    profiles:
      - test
    build:
      dockerfile: Dockerfile.build
    entrypoint: /app/run.sh
    volumes:
      - "./tests/integration/test_build_move_starter_code/studentTests:/app/source/studentTests"
      - "./tests/integration/test_build_move_starter_code/run.sh:/app/run.sh"
      - "./tests/integration/test_build_move_starter_code/bin:/app/bin"

  test_build_move_data_files:
    profiles:
      - test
    build:
      dockerfile: Dockerfile.build
    entrypoint: /app/run.sh
    volumes:
      - "./tests/integration/test_build_move_data_files/studentTests:/app/source/studentTests"
      - "./tests/integration/test_build_move_data_files/run.sh:/app/run.sh"
      - "./tests/integration/test_build_move_data_files/bin:/app/bin"



