version: "3"
services:
  test_many_non_main_files:
    build:
      dockerfile: Dockerfile
    entrypoint: /autograder/run_autograder
    volumes:
      - "./tests/integration/test_many_non_main_files/results:/autograder/results"
      - "./tests/integration/test_many_non_main_files/studentTests:/autograder/source/studentTests"
      - "./tests/integration/test_many_non_main_files/submission:/autograder/submission"
      - "./tests/integration/test_many_non_main_files/submission_metadata.json:/autograder/submission_metadata.json"
      - "./tests/integration/integration_config.toml:/autograder/source/config.toml"


  test_build:
    build:
      dockerfile: Dockerfile.build
    entrypoint: sh /app/run.sh
    volumes:
      - "./tests/integration/test_build/studentTests:/app/source/studentTests"
      - "./tests/integration/test_build/run.sh:/app/run.sh"
      - "./tests/integration/test_build/bin:/app/bin"
      - "./tests/integration/integration_config.toml:/app/source/config.toml"
      - "./tests/integration/test_build/starter_code/:/app/source/starter_code"



