version: "3"
services:
  test_no_previous_submissions:
    profiles:
      - test
    build:
      dockerfile: Dockerfile
    entrypoint: /autograder/run_autograder
    volumes:
      - "./integration/test_no_previous_submissions/results:/autograder/results"
      - "./integration/test_no_previous_submissions/studentTests:/autograder/source/studentTests"
      - "./integration/test_no_previous_submissions/submission:/autograder/submission"
      - "./integration/test_no_previous_submissions/submission_metadata.json:/autograder/submission_metadata.json"

  test_lower_previous_submissions:
    profiles:
      - test
    build:
      dockerfile: Dockerfile
    entrypoint: /autograder/run_autograder
    volumes:
      - "./integration/test_lower_previous_submissions/results:/autograder/results"
      - "./integration/test_lower_previous_submissions/studentTests:/autograder/source/studentTests"
      - "./integration/test_lower_previous_submissions/submission:/autograder/submission"
      - "./integration/test_lower_previous_submissions/submission_metadata.json:/autograder/submission_metadata.json"

  test_higher_previous_submissions:
    profiles:
      - test
    build:
      dockerfile: Dockerfile
    entrypoint: /autograder/run_autograder
    volumes:
      - "./integration/test_higher_previous_submissions/results:/autograder/results"
      - "./integration/test_higher_previous_submissions/studentTests:/autograder/source/studentTests"
      - "./integration/test_higher_previous_submissions/submission:/autograder/submission"
      - "./integration/test_higher_previous_submissions/submission_metadata.json:/autograder/submission_metadata.json"

  test_lower_previous_limit_exceeded:
    profiles:
      - test
    build:
      dockerfile: Dockerfile
    entrypoint: /autograder/run_autograder
    volumes:
      - "./integration/test_lower_previous_limit_exceeded/results:/autograder/results"
      - "./integration/test_lower_previous_limit_exceeded/studentTests:/autograder/source/studentTests"
      - "./integration/test_lower_previous_limit_exceeded/submission:/autograder/submission"
      - "./integration/test_lower_previous_limit_exceeded/submission_metadata.json:/autograder/submission_metadata.json"

  test_submission_name_with_spaces:
    profiles:
      - test
    build:
      dockerfile: Dockerfile
    entrypoint: /autograder/run_autograder
    volumes:
      - "./integration/test_submission_name_with_spaces/results:/autograder/results"
      - "./integration/test_submission_name_with_spaces/studentTests:/autograder/source/studentTests"
      - "./integration/test_submission_name_with_spaces/submission:/autograder/submission"
      - "./integration/test_submission_name_with_spaces/submission_metadata.json:/autograder/submission_metadata.json"

  test_many_non_main_files:
    profiles:
      - test
    build:
      dockerfile: Dockerfile
    entrypoint: /autograder/run_autograder
    volumes:
      - "./integration/test_many_non_main_files/results:/autograder/results"
      - "./integration/test_many_non_main_files/studentTests:/autograder/source/studentTests"
      - "./integration/test_many_non_main_files/submission:/autograder/submission"
      - "./integration/test_many_non_main_files/submission_metadata.json:/autograder/submission_metadata.json"

  test_build_move_test_cases:
    profiles:
      - test
    build:
      dockerfile: Dockerfile.build
    entrypoint: /app/run.sh
    volumes:
      - "./integration/test_build_move_test_cases/studentTests:/app/source/studentTests"
      - "./integration/test_build_move_test_cases/run.sh:/app/run.sh"
      - "./integration/test_build_move_test_cases/bin:/app/bin"

  test_build_move_starter_code:
    profiles:
      - test
    build:
      dockerfile: Dockerfile.build
    entrypoint: /app/run.sh
    volumes:
      - "./integration/test_build_move_starter_code/studentTests:/app/source/studentTests"
      - "./integration/test_build_move_starter_code/run.sh:/app/run.sh"
      - "./integration/test_build_move_starter_code/bin:/app/bin"
