name: Integration Tests
on:
  push

jobs:
  test:
    name: Run Integration Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Build container for tests
      run: docker compose build

    - name: Run tests
      run: docker compose up

    - name: Verify test outputs
      run: bash tests/integration/verify.sh
